# Generated by Django 4.2.7 on 2023-11-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HrManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('surname', models.CharField(default=None, max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('birthday', models.DateField()),
                ('birthplace', models.CharField(max_length=50)),
                ('profilepicture',
                 models.ImageField(blank=True, default='default.jpg', null=True, upload_to='hrmanager_profile_pics/')),
            ],
        ),
    ]
