# Generated by Django 4.2.7 on 2023-11-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('hr_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', max_length=100)),
                ('surname', models.CharField(default=None, max_length=100)),
                ('application_deadline', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('birthday', models.DateField()),
                ('birthplace', models.CharField(max_length=50)),
                ('profilepicture',
                 models.ImageField(blank=True, default='default.jpg', null=True, upload_to='recruits_profile_pics/')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='hr_manager.department')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.TextField(default=None, max_length=100)),
                (
                'employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_manager.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('training', models.TextField(default=None, max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_manager.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.TextField(default=None)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_manager.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveAndAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                (
                'employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_manager.recruit')),
            ],
        ),
    ]
