# Generated by Django 4.2.7 on 2023-11-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_manager', '0003_hrmanager_user_recruit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveandattendance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='recruittraining',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
