# Generated by Django 4.2.7 on 2023-11-12 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('hr_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('profilepicture',
                 models.ImageField(blank=True, default='default.jpg', null=True, upload_to='employee_profile_pics/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('department',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_manager.department')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.TextField(default=None, max_length=100)),
                ('employee',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employeeinformation')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveAndAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('employee',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employeeinformation')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('employee',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employeeinformation')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.TextField(default=None)),
                ('employee',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employeeinformation')),
            ],
        ),
    ]
