# Generated by Django 4.2.7 on 2023-11-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeinformation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetraining',
            name='status',
        ),
        migrations.AlterField(
            model_name='leaveandattendance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
