# Generated by Django 4.2.7 on 2023-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employeetraining_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeperformance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
